// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/converter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoConvertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoConvertRequest) Reset() {
	*x = DoConvertRequest{}
	mi := &file_proto_converter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoConvertRequest) ProtoMessage() {}

func (x *DoConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_converter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoConvertRequest.ProtoReflect.Descriptor instead.
func (*DoConvertRequest) Descriptor() ([]byte, []int) {
	return file_proto_converter_proto_rawDescGZIP(), []int{0}
}

func (x *DoConvertRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DoConvertRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *DoConvertRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DoConvertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Result        float64                `protobuf:"fixed64,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoConvertResponse) Reset() {
	*x = DoConvertResponse{}
	mi := &file_proto_converter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoConvertResponse) ProtoMessage() {}

func (x *DoConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_converter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoConvertResponse.ProtoReflect.Descriptor instead.
func (*DoConvertResponse) Descriptor() ([]byte, []int) {
	return file_proto_converter_proto_rawDescGZIP(), []int{1}
}

func (x *DoConvertResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DoConvertResponse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *DoConvertResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *DoConvertResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DoConvertResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type GetCurrencyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyListRequest) Reset() {
	*x = GetCurrencyListRequest{}
	mi := &file_proto_converter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyListRequest) ProtoMessage() {}

func (x *GetCurrencyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_converter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyListRequest.ProtoReflect.Descriptor instead.
func (*GetCurrencyListRequest) Descriptor() ([]byte, []int) {
	return file_proto_converter_proto_rawDescGZIP(), []int{2}
}

type GetCurrencyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []string               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyListResponse) Reset() {
	*x = GetCurrencyListResponse{}
	mi := &file_proto_converter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyListResponse) ProtoMessage() {}

func (x *GetCurrencyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_converter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyListResponse.ProtoReflect.Descriptor instead.
func (*GetCurrencyListResponse) Descriptor() ([]byte, []int) {
	return file_proto_converter_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrencyListResponse) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_converter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_converter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_converter_proto_rawDescGZIP(), []int{4}
}

var File_proto_converter_proto protoreflect.FileDescriptor

const file_proto_converter_proto_rawDesc = "" +
	"\n" +
	"\x15proto/converter.proto\x12\x05proto\"N\n" +
	"\x10DoConvertRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"{\n" +
	"\x11DoConvertResponse\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06result\x18\x05 \x01(\x01R\x06result\"\x18\n" +
	"\x16GetCurrencyListRequest\"-\n" +
	"\x17GetCurrencyListResponse\x12\x12\n" +
	"\x04list\x18\x01 \x03(\tR\x04list\"\a\n" +
	"\x05Empty2\xa8\x01\n" +
	"\x10ConverterService\x12R\n" +
	"\x0fGetCurrencyList\x12\x1d.proto.GetCurrencyListRequest\x1a\x1e.proto.GetCurrencyListResponse\"\x00\x12@\n" +
	"\tDoConvert\x12\x17.proto.DoConvertRequest\x1a\x18.proto.DoConvertResponse\"\x00B\x15Z\x13curr-conv-api/protob\x06proto3"

var (
	file_proto_converter_proto_rawDescOnce sync.Once
	file_proto_converter_proto_rawDescData []byte
)

func file_proto_converter_proto_rawDescGZIP() []byte {
	file_proto_converter_proto_rawDescOnce.Do(func() {
		file_proto_converter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_converter_proto_rawDesc), len(file_proto_converter_proto_rawDesc)))
	})
	return file_proto_converter_proto_rawDescData
}

var file_proto_converter_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_converter_proto_goTypes = []any{
	(*DoConvertRequest)(nil),        // 0: proto.DoConvertRequest
	(*DoConvertResponse)(nil),       // 1: proto.DoConvertResponse
	(*GetCurrencyListRequest)(nil),  // 2: proto.GetCurrencyListRequest
	(*GetCurrencyListResponse)(nil), // 3: proto.GetCurrencyListResponse
	(*Empty)(nil),                   // 4: proto.Empty
}
var file_proto_converter_proto_depIdxs = []int32{
	2, // 0: proto.ConverterService.GetCurrencyList:input_type -> proto.GetCurrencyListRequest
	0, // 1: proto.ConverterService.DoConvert:input_type -> proto.DoConvertRequest
	3, // 2: proto.ConverterService.GetCurrencyList:output_type -> proto.GetCurrencyListResponse
	1, // 3: proto.ConverterService.DoConvert:output_type -> proto.DoConvertResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_converter_proto_init() }
func file_proto_converter_proto_init() {
	if File_proto_converter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_converter_proto_rawDesc), len(file_proto_converter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_converter_proto_goTypes,
		DependencyIndexes: file_proto_converter_proto_depIdxs,
		MessageInfos:      file_proto_converter_proto_msgTypes,
	}.Build()
	File_proto_converter_proto = out.File
	file_proto_converter_proto_goTypes = nil
	file_proto_converter_proto_depIdxs = nil
}
