// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/converter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConverterService_GetCurrencyList_FullMethodName = "/proto.ConverterService/GetCurrencyList"
	ConverterService_DoConvert_FullMethodName       = "/proto.ConverterService/DoConvert"
)

// ConverterServiceClient is the client API for ConverterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConverterServiceClient interface {
	GetCurrencyList(ctx context.Context, in *GetCurrencyListRequest, opts ...grpc.CallOption) (*GetCurrencyListResponse, error)
	DoConvert(ctx context.Context, in *DoConvertRequest, opts ...grpc.CallOption) (*DoConvertResponse, error)
}

type converterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConverterServiceClient(cc grpc.ClientConnInterface) ConverterServiceClient {
	return &converterServiceClient{cc}
}

func (c *converterServiceClient) GetCurrencyList(ctx context.Context, in *GetCurrencyListRequest, opts ...grpc.CallOption) (*GetCurrencyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrencyListResponse)
	err := c.cc.Invoke(ctx, ConverterService_GetCurrencyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *converterServiceClient) DoConvert(ctx context.Context, in *DoConvertRequest, opts ...grpc.CallOption) (*DoConvertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoConvertResponse)
	err := c.cc.Invoke(ctx, ConverterService_DoConvert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConverterServiceServer is the server API for ConverterService service.
// All implementations must embed UnimplementedConverterServiceServer
// for forward compatibility.
type ConverterServiceServer interface {
	GetCurrencyList(context.Context, *GetCurrencyListRequest) (*GetCurrencyListResponse, error)
	DoConvert(context.Context, *DoConvertRequest) (*DoConvertResponse, error)
	mustEmbedUnimplementedConverterServiceServer()
}

// UnimplementedConverterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConverterServiceServer struct{}

func (UnimplementedConverterServiceServer) GetCurrencyList(context.Context, *GetCurrencyListRequest) (*GetCurrencyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrencyList not implemented")
}
func (UnimplementedConverterServiceServer) DoConvert(context.Context, *DoConvertRequest) (*DoConvertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoConvert not implemented")
}
func (UnimplementedConverterServiceServer) mustEmbedUnimplementedConverterServiceServer() {}
func (UnimplementedConverterServiceServer) testEmbeddedByValue()                          {}

// UnsafeConverterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConverterServiceServer will
// result in compilation errors.
type UnsafeConverterServiceServer interface {
	mustEmbedUnimplementedConverterServiceServer()
}

func RegisterConverterServiceServer(s grpc.ServiceRegistrar, srv ConverterServiceServer) {
	// If the following call pancis, it indicates UnimplementedConverterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConverterService_ServiceDesc, srv)
}

func _ConverterService_GetCurrencyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrencyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConverterServiceServer).GetCurrencyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConverterService_GetCurrencyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConverterServiceServer).GetCurrencyList(ctx, req.(*GetCurrencyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConverterService_DoConvert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConverterServiceServer).DoConvert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConverterService_DoConvert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConverterServiceServer).DoConvert(ctx, req.(*DoConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConverterService_ServiceDesc is the grpc.ServiceDesc for ConverterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConverterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ConverterService",
	HandlerType: (*ConverterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrencyList",
			Handler:    _ConverterService_GetCurrencyList_Handler,
		},
		{
			MethodName: "DoConvert",
			Handler:    _ConverterService_DoConvert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/converter.proto",
}
