syntax = "proto3";
package proto;

option go_package = "curr-conv-api/proto";
service ConverterService {
    rpc GetCurrencyList(GetCurrencyListRequest) returns (GetCurrencyListResponse) {}
    rpc DoConvert(DoConvertRequest) returns (DoConvertResponse) {}
}

message DoConvertRequest {
    string from = 1;
    string to = 2;
    double amount = 3;
}

message DoConvertResponse {
    string from = 1;
    string to = 2;
    double rate = 3;
    double amount = 4;
    double result = 5;
}

message GetCurrencyListRequest {}

message GetCurrencyListResponse {
    repeated string list = 1;
}

message Empty {}